apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-api-ingress
  namespace: notes-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: notes-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notes-api-service
                port:
                  number: 3000
