apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "notes-api.fullname" . }}
  labels:
    release: monitoring   # <--- ðŸŸ¢ CHANGE THIS LINE (was kube-prometheus-stack)
spec:
  selector:
    matchLabels:
      {{- include "notes-api.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 10s